name: Deploy WSAC Backend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Desplegar en AWS vía SSH
        uses: appleboy/ssh-action@master
        with:
          host: 3.133.217.145
          username: Administrator
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          fingerprint: ""
          script: |
            cd /d C:\Users\Administrator\Documents\WSAC_PROD
            git fetch --all
            git reset --hard origin/main
            npm install --production
            pm2 delete wsac 2>nul || echo Proceso no existia
            pm2 start server.js --name wsac --update-env
            pm2 save
